name: CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    # Add DATABASE_URL environment variable to the job
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      # Step 1: Check out code
      - name: Check out code
        uses: actions/checkout@v4

      # Step 2: Set up Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.x
      
      # Step 3: Install Goose (for database migrations)
      - name: Install Goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest

      # Step 4: Build the app
      - name: Build production app
        run: scripts/buildprod.sh

      # Step 5: Run database migrations
      - name: Run database migrations
        run: |
          goose -dir migrations postgres "$DATABASE_URL" up

      # Step 6: Authenticate with GCP
      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # Step 7: Set up gcloud CLI
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: notely-447316
          install_components: "gcloud"

      # Step 8: Build and push Docker image to Artifact Registry
      - name: Build and Push Docker Image
        run: |
          gcloud builds submit --tag us-central1-docker.pkg.dev/notely-447316/notely-ar-repo/notely:latest .

      # Step 9: Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy notely \
            --image us-central1-docker.pkg.dev/notely-447316/notely-ar-repo/notely:latest \
            --region us-central1 \
            --allow-unauthenticated \
            --project notely-447316 \
            --max-instances=4
